import score1 from "../assets/score1.svg";
import score2 from "../assets/score2.svg";
import logo from "../assets/googlelogo.svg";

const Jobs = [
    {
        id: 1,
        title: "UI/UX Designer",
        company: "Google",
        skills: {
            one: "Figma",
            two: "Prototyping",
            three: "User Interface",
        },
        experience: "0-3 Years",
        jobType: "Full Time",
        postedOn: "02 April 2024",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        description1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        scoreImg: `${score1}`,
        logo: `${logo}`,
    },
    {
        id: 2,
        title: "UI/UX Designer",
        company: "Google",
        skills: {
            one: "Figma",
            two: "Prototyping",
            three: "User Interface",
        },
        experience: "0-3 Years",
        jobType: "Full Time",
        postedOn: "02 April 2024",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        description1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        scoreImg: `${score2}`,
        logo: `${logo}`,
    },
    {
        id: 3,
        title: "UI/UX Designer",
        company: "Google",
        skills: {
            one: "Figma",
            two: "Prototyping",
            three: "User Interface",
        },
        experience: "0-3 Years",
        jobType: "Full Time",
        postedOn: "02 April 2024",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        description1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        scoreImg: `${score2}`,
        logo: `${logo}`,
    },
    {
        id: 4,
        title: "UI/UX Designer",
        company: "Google",
        skills: {
            one: "Figma",
            two: "Prototyping",
            three: "User Interface",
        },
        experience: "0-3 Years",
        jobType: "Full Time",
        postedOn: "02 April 2024",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        description1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        scoreImg: `${score2}`,
        logo: `${logo}`,
    },
    {
        id: 5,
        title: "UI/UX Designer",
        company: "Google",
        skills: {
            one: "Figma",
            two: "Prototyping",
            three: "User Interface",
        },
        experience: "0-3 Years",
        jobType: "Full Time",
        postedOn: "02 April 2024",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        description1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        scoreImg: `${score2}`,
        logo: `${logo}`,
    },
    {
        id: 6,
        title: "UI/UX Designer",
        company: "Google",
        skills: {
            one: "Figma",
            two: "Prototyping",
            three: "User Interface",
        },
        experience: "0-3 Years",
        jobType: "Full Time",
        postedOn: "02 April 2024",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        description1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
        scoreImg: `${score2}`,
        logo: `${logo}`,
    },
];

export default Jobs;
